# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_workf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pr-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test with MyPy
      shell: bash
      run: |
        echo "TESTING"
        git diff --name-only --diff-filter=ACM origin/main..HEAD > 1.txt
        git diff --name-only --diff-filter=ACM origin/main > 2.txt
        git diff --name-only --diff-filter=ACM main > 3.txt
        git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > 4.txt
        git diff --name-only HEAD^ HEAD > 5.txt
        echo "CAT1"
        cat 1.txt
        echo "CAT2"
        cat 2.txt
        echo "CAT3"
        cat 3.txt
        echo "CAT4"
        cat 4.txt
        echo "CAT5"
        cat 5.txt

#        echo "GREP"
#        grep "py" test.txt

#      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV

#     - name: Install poetry
#       run: |
#         python -m pip install poetry==1.1.12
#         poetry config virtualenvs.create false
#     - name: Install dependencies
#       run: |
#         poetry install --no-root
#     - name: Lint with flake8
#       run: |
#         flake8
#    - name: Test with pytest
#      run: |
#        pytest
