# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_workf

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pr-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
#     - name: Install poetry
#       run: |
#         python -m pip install poetry==1.1.12
#         poetry config virtualenvs.create false
#     - name: Install dependencies
#       run: |
#         poetry install --no-root
#     - name: Lint with flake8
#       run: |
#         flake8
#    - name: Test with pytest
#      run: |
#        pytest
    - name: Test with MyPy
      run: |
        echo "test"
        git diff --name-only --diff-filter=ACM origin/${GITHUB_BASE_REF:-main} | grep ".py$"
#        echo ${PIPESTATUS[0]} ${PIPESTATUS[2]} | grep -qE '^[0 ]+$'
#        git diff --name-only --diff-filter=ACM origin/${GITHUB_BASE_REF:-master}

