# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_workf

on:
  push:
    branches: [main]

jobs:
  pr-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test with MyPy
      shell: bash
      run: |
        git fetch origin main.main
        echo "TESTING"
        git diff --name-only --diff-filter=ACM main > test.txt
        echo "CAT"
        cat test.txt
        echo "GREP"
        grep "py" test.txt

#      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV

#     - name: Install poetry
#       run: |
#         python -m pip install poetry==1.1.12
#         poetry config virtualenvs.create false
#     - name: Install dependencies
#       run: |
#         poetry install --no-root
#     - name: Lint with flake8
#       run: |
#         flake8
#    - name: Test with pytest
#      run: |
#        pytest
